export enum BlockType {
  AIR = 0,
  GRASS = 1,
  DIRT = 2,
  STONE = 3,
  WOOD = 4,
  LEAVES = 5,
  PLANK = 6,
  BRICK = 7,
  GLASS = 8,
  COBBLESTONE = 9,
  SAND = 10,
  DIAMOND_ORE = 11,
  // Additional decorative & building blocks
  OBSIDIAN = 12,
  GOLD_BLOCK = 13,
  TNT = 14,
  BOOKSHELF = 15,
  GLOWSTONE = 16,
  // Tools & Weapons
  DIAMOND_AXE = 17,
  DIAMOND_PICKAXE = 18,
  DIAMOND_SWORD = 19,
  DIAMOND_SHOVEL = 20,
  // Animals & Spawn Eggs
  DUCK_SPAWN_EGG = 21,
  CHICKEN_SPAWN_EGG = 22,
  SHEEP_SPAWN_EGG = 23,
  COW_SPAWN_EGG = 24,
  // Food & Items
  GOLDEN_APPLE = 25,
  WHEAT = 26,
  // Crafting & Workstation
  CRAFTING_TABLE = 27,
  STICK = 28,
  WOODEN_PICKAXE = 29,
  WOODEN_SWORD = 30,
  WOODEN_AXE = 31,
  // Monster Drops & Materials
  ROTTEN_FLESH = 32,
  SLIME_BALL = 33,
  BONE = 34,
  DIAMOND = 35,
  BREAD = 36,
  // Monster Spawn Eggs
  ZOMBIE_SPAWN_EGG = 37,
  SLIME_SPAWN_EGG = 38,
  // Natural & Lighting Elements
  TORCH = 39,
  WATER = 40,
  GRAVEL = 41,
  COAL = 42,
  IRON_INGOT = 43,
  // Additional Tools
  IRON_PICKAXE = 44,
  IRON_AXE = 45,
  IRON_SHOVEL = 46,
  IRON_SWORD = 47,
  WOODEN_SHOVEL = 48,
  // Terrain / Biome Blocks
  SNOW = 49,
}

export enum ItemCategory {
  BLOCK = "block",
  TOOL = "tool",
  SPAWN_EGG = "egg",
  FOOD = "item",
}

export type AnimalType = "duck" | "chicken" | "sheep" | "cow";
export type MobType = "zombie" | "slime";
export type CreatureType = AnimalType | MobType;

export type ToolType = "pickaxe" | "axe" | "shovel" | "sword" | "none";
export type ToolMaterial = "wood" | "iron" | "diamond";

export interface ToolStats {
  toolType: ToolType;
  material: ToolMaterial;
  maxDurability: number;
  miningSpeedMultiplier: number;
  attackDamage: number;
}

export interface BlockMeta {
  id: BlockType;
  name: string;
  nameKo: string;
  solid: boolean;
  transparent: boolean;
  color: string; // Fallback color
  textureType: string;
  soundType: "grass" | "dirt" | "stone" | "wood" | "glass" | "sand" | "cloth" | "metal";
  category: ItemCategory | "block" | "tool" | "egg" | "item";
  isTool?: boolean;
  isEgg?: boolean;
  spawnType?: CreatureType;
  isPlaceable?: boolean;
  description?: string;
  damage?: number;
  hardness?: number; // Base break time in seconds
  preferredTool?: ToolType;
  gravityAffected?: boolean; // Sand, Gravel fall downward
  isFluid?: boolean; // Water
  lightLevel?: number; // Torch: 14, Glowstone: 15
  toolStats?: ToolStats;
}

export const BLOCK_DEFINITIONS: Record<BlockType, BlockMeta> = {
  [BlockType.AIR]: {
    id: BlockType.AIR,
    name: "Air",
    nameKo: "공기",
    solid: false,
    transparent: true,
    color: "#000000",
    textureType: "air",
    soundType: "dirt",
    category: "block",
    isPlaceable: false,
  },
  [BlockType.GRASS]: {
    id: BlockType.GRASS,
    name: "Grass Block",
    nameKo: "잔디 블록",
    solid: true,
    transparent: false,
    color: "#5b8c32",
    textureType: "grass",
    soundType: "grass",
    category: "block",
    isPlaceable: true,
    hardness: 0.6,
    preferredTool: "shovel",
    description: "초원을 이루는 기본 잔디 블록입니다.",
  },
  [BlockType.DIRT]: {
    id: BlockType.DIRT,
    name: "Dirt",
    nameKo: "흙",
    solid: true,
    transparent: false,
    color: "#866043",
    textureType: "dirt",
    soundType: "dirt",
    category: "block",
    isPlaceable: true,
    hardness: 0.5,
    preferredTool: "shovel",
    description: "풍부한 영양을 머금은 흙 블록입니다.",
  },
  [BlockType.STONE]: {
    id: BlockType.STONE,
    name: "Stone",
    nameKo: "돌",
    solid: true,
    transparent: false,
    color: "#757575",
    textureType: "stone",
    soundType: "stone",
    category: "block",
    isPlaceable: true,
    hardness: 1.5,
    preferredTool: "pickaxe",
    description: "지하 깊은 곳의 단단한 천연 암석입니다.",
  },
  [BlockType.WOOD]: {
    id: BlockType.WOOD,
    name: "Oak Log",
    nameKo: "참나무 원목",
    solid: true,
    transparent: false,
    color: "#674c2e",
    textureType: "wood",
    soundType: "wood",
    category: "block",
    isPlaceable: true,
    hardness: 2.0,
    preferredTool: "axe",
    description: "나무 기둥을 이루는 튼튼한 원목입니다.",
  },
  [BlockType.LEAVES]: {
    id: BlockType.LEAVES,
    name: "Oak Leaves",
    nameKo: "참나무 잎",
    solid: true,
    transparent: true,
    color: "#38761d",
    textureType: "leaves",
    soundType: "grass",
    category: "block",
    isPlaceable: true,
    description: "싱그러운 잎사귀 블록입니다.",
  },
  [BlockType.PLANK]: {
    id: BlockType.PLANK,
    name: "Oak Planks",
    nameKo: "참나무 판자",
    solid: true,
    transparent: false,
    color: "#b48448",
    textureType: "plank",
    soundType: "wood",
    category: "block",
    isPlaceable: true,
    description: "건축에 이상적인 가공된 목재 판자입니다.",
  },
  [BlockType.BRICK]: {
    id: BlockType.BRICK,
    name: "Bricks",
    nameKo: "벽돌",
    solid: true,
    transparent: false,
    color: "#964b36",
    textureType: "brick",
    soundType: "stone",
    category: "block",
    isPlaceable: true,
    description: "붉은 점토로 구워낸 클래식한 벽돌입니다.",
  },
  [BlockType.GLASS]: {
    id: BlockType.GLASS,
    name: "Glass",
    nameKo: "유리",
    solid: true,
    transparent: true,
    color: "#a0d2eb",
    textureType: "glass",
    soundType: "glass",
    category: "block",
    isPlaceable: true,
    description: "투명하고 시원한 채광용 유리 블록입니다.",
  },
  [BlockType.COBBLESTONE]: {
    id: BlockType.COBBLESTONE,
    name: "Cobblestone",
    nameKo: "조약돌",
    solid: true,
    transparent: false,
    color: "#5c5c5c",
    textureType: "cobblestone",
    soundType: "stone",
    category: "block",
    isPlaceable: true,
    hardness: 2.0,
    preferredTool: "pickaxe",
    description: "채굴하여 얻은 거친 질감의 석재입니다.",
  },
  [BlockType.SAND]: {
    id: BlockType.SAND,
    name: "Sand",
    nameKo: "모래",
    solid: true,
    transparent: false,
    color: "#d9c882",
    textureType: "sand",
    soundType: "sand",
    category: "block",
    isPlaceable: true,
    gravityAffected: true,
    hardness: 0.5,
    preferredTool: "shovel",
    description: "해변이나 사막의 고운 모래 블록입니다. 지지대가 없으면 아래로 떨어집니다.",
  },
  [BlockType.DIAMOND_ORE]: {
    id: BlockType.DIAMOND_ORE,
    name: "Diamond Ore",
    nameKo: "다이아몬드 원석",
    solid: true,
    transparent: false,
    color: "#3be3db",
    textureType: "diamond_ore",
    soundType: "stone",
    category: "block",
    isPlaceable: true,
    hardness: 3.0,
    preferredTool: "pickaxe",
    description: "희귀하고 영롱하게 빛나는 다이아몬드 광물입니다.",
  },
  [BlockType.OBSIDIAN]: {
    id: BlockType.OBSIDIAN,
    name: "Obsidian",
    nameKo: "흑요석",
    solid: true,
    transparent: false,
    color: "#1d1233",
    textureType: "obsidian",
    soundType: "stone",
    category: "block",
    isPlaceable: true,
    description: "용암과 물이 만나 형성된 가장 단단한 암석입니다.",
  },
  [BlockType.GOLD_BLOCK]: {
    id: BlockType.GOLD_BLOCK,
    name: "Gold Block",
    nameKo: "금 블록",
    solid: true,
    transparent: false,
    color: "#ffd700",
    textureType: "gold_block",
    soundType: "metal",
    category: "block",
    isPlaceable: true,
    description: "순금으로 제련된 눈부신 황금 블록입니다.",
  },
  [BlockType.TNT]: {
    id: BlockType.TNT,
    name: "TNT",
    nameKo: "TNT 폭약",
    solid: true,
    transparent: false,
    color: "#db3223",
    textureType: "tnt",
    soundType: "grass",
    category: "block",
    isPlaceable: true,
    description: "폭발적인 위력을 자랑하는 화약 블록입니다.",
  },
  [BlockType.BOOKSHELF]: {
    id: BlockType.BOOKSHELF,
    name: "Bookshelf",
    nameKo: "책장",
    solid: true,
    transparent: false,
    color: "#8a6136",
    textureType: "bookshelf",
    soundType: "wood",
    category: "block",
    isPlaceable: true,
    description: "다양한 서적이 꽂혀 있는 고풍스러운 원목 책장입니다.",
  },
  [BlockType.GLOWSTONE]: {
    id: BlockType.GLOWSTONE,
    name: "Glowstone",
    nameKo: "발광석",
    solid: true,
    transparent: false,
    color: "#ffd966",
    textureType: "glowstone",
    soundType: "glass",
    category: "block",
    isPlaceable: true,
    description: "어둠 속에서도 자체적으로 밝은 빛을 내뿜는 광석입니다.",
  },
  // Tools
  [BlockType.DIAMOND_AXE]: {
    id: BlockType.DIAMOND_AXE,
    name: "Diamond Axe",
    nameKo: "다이아몬드 도끼",
    solid: false,
    transparent: true,
    color: "#38bdf8",
    textureType: "diamond_axe",
    soundType: "metal",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 7,
    toolStats: {
      toolType: "axe",
      material: "diamond",
      maxDurability: 1561,
      miningSpeedMultiplier: 8,
      attackDamage: 7,
    },
    description: "원목과 판자를 눈 깜짝할 사이에 베어내는 전설의 도끼입니다.",
  },
  [BlockType.DIAMOND_PICKAXE]: {
    id: BlockType.DIAMOND_PICKAXE,
    name: "Diamond Pickaxe",
    nameKo: "다이아몬드 곡괭이",
    solid: false,
    transparent: true,
    color: "#38bdf8",
    textureType: "diamond_pickaxe",
    soundType: "metal",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 5,
    toolStats: {
      toolType: "pickaxe",
      material: "diamond",
      maxDurability: 1561,
      miningSpeedMultiplier: 10,
      attackDamage: 5,
    },
    description: "흑요석과 바위를 강력하게 파쇄하는 최고급 곡괭이입니다.",
  },
  [BlockType.DIAMOND_SWORD]: {
    id: BlockType.DIAMOND_SWORD,
    name: "Diamond Sword",
    nameKo: "다이아몬드 검",
    solid: false,
    transparent: true,
    color: "#38bdf8",
    textureType: "diamond_sword",
    soundType: "metal",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 8,
    toolStats: {
      toolType: "sword",
      material: "diamond",
      maxDurability: 1561,
      miningSpeedMultiplier: 2,
      attackDamage: 8,
    },
    description: "날카로운 칼날과 공격력을 자랑하는 전투용 명검입니다.",
  },
  [BlockType.DIAMOND_SHOVEL]: {
    id: BlockType.DIAMOND_SHOVEL,
    name: "Diamond Shovel",
    nameKo: "다이아몬드 삽",
    solid: false,
    transparent: true,
    color: "#38bdf8",
    textureType: "diamond_shovel",
    soundType: "metal",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 4,
    toolStats: {
      toolType: "shovel",
      material: "diamond",
      maxDurability: 1561,
      miningSpeedMultiplier: 8,
      attackDamage: 4,
    },
    description: "흙과 모래를 초고속으로 파내는 가볍고 단단한 삽입니다.",
  },
  // Spawn Eggs
  [BlockType.DUCK_SPAWN_EGG]: {
    id: BlockType.DUCK_SPAWN_EGG,
    name: "Duck Spawn Egg",
    nameKo: "오리 소환 알",
    solid: false,
    transparent: true,
    color: "#22c55e",
    textureType: "duck_egg",
    soundType: "grass",
    category: "egg",
    isEgg: true,
    spawnType: "duck",
    isPlaceable: false,
    description: "우클릭하여 귀엽게 꽥꽥거리는 청둥오리를 소환합니다.",
  },
  [BlockType.CHICKEN_SPAWN_EGG]: {
    id: BlockType.CHICKEN_SPAWN_EGG,
    name: "Chicken Spawn Egg",
    nameKo: "닭 소환 알",
    solid: false,
    transparent: true,
    color: "#f87171",
    textureType: "chicken_egg",
    soundType: "grass",
    category: "egg",
    isEgg: true,
    spawnType: "chicken",
    isPlaceable: false,
    description: "우클릭하여 날개를 파닥거리며 모이를 쪼는 닭을 소환합니다.",
  },
  [BlockType.SHEEP_SPAWN_EGG]: {
    id: BlockType.SHEEP_SPAWN_EGG,
    name: "Sheep Spawn Egg",
    nameKo: "양 소환 알",
    solid: false,
    transparent: true,
    color: "#e2e8f0",
    textureType: "sheep_egg",
    soundType: "grass",
    category: "egg",
    isEgg: true,
    spawnType: "sheep",
    isPlaceable: false,
    description: "우클릭하여 포근한 털을 가진 순한 양을 소환합니다.",
  },
  [BlockType.COW_SPAWN_EGG]: {
    id: BlockType.COW_SPAWN_EGG,
    name: "Cow Spawn Egg",
    nameKo: "소 소환 알",
    solid: false,
    transparent: true,
    color: "#a16207",
    textureType: "cow_egg",
    soundType: "grass",
    category: "egg",
    isEgg: true,
    spawnType: "cow",
    isPlaceable: false,
    description: "우클릭하여 얼룩무늬가 매력적인 젖소를 소환합니다.",
  },
  // Food & Items
  [BlockType.GOLDEN_APPLE]: {
    id: BlockType.GOLDEN_APPLE,
    name: "Golden Apple",
    nameKo: "황금 사과",
    solid: false,
    transparent: true,
    color: "#fbbf24",
    textureType: "golden_apple",
    soundType: "grass",
    category: "item",
    isPlaceable: false,
    description: "신비로운 에너지를 지닌 황금 사과입니다. 우클릭 시 먹을 수 있습니다.",
  },
  [BlockType.WHEAT]: {
    id: BlockType.WHEAT,
    name: "Wheat",
    nameKo: "밀 (동물 먹이)",
    solid: false,
    transparent: true,
    color: "#eab308",
    textureType: "wheat",
    soundType: "grass",
    category: "item",
    isPlaceable: false,
    description: "오리, 닭, 양, 소가 좋아하는 싱싱한 밀 줄기입니다. 우클릭으로 먹이를 줍니다.",
  },
  [BlockType.CRAFTING_TABLE]: {
    id: BlockType.CRAFTING_TABLE,
    name: "Crafting Table",
    nameKo: "제작대 (조합대)",
    solid: true,
    transparent: false,
    color: "#a16207",
    textureType: "crafting_table",
    soundType: "wood",
    category: "block",
    isPlaceable: true,
    description: "다양한 도구와 블록을 정교하게 제작할 수 있는 3x3 조합대입니다.",
  },
  [BlockType.STICK]: {
    id: BlockType.STICK,
    name: "Stick",
    nameKo: "막대기",
    solid: false,
    transparent: true,
    color: "#78350f",
    textureType: "stick",
    soundType: "wood",
    category: "item",
    isPlaceable: false,
    description: "도구와 무기의 손잡이로 쓰이는 가느다란 나무 막대기입니다.",
  },
  [BlockType.WOODEN_PICKAXE]: {
    id: BlockType.WOODEN_PICKAXE,
    name: "Wooden Pickaxe",
    nameKo: "나무 곡괭이",
    solid: false,
    transparent: true,
    color: "#b45309",
    textureType: "wooden_pickaxe",
    soundType: "wood",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 2,
    toolStats: {
      toolType: "pickaxe",
      material: "wood",
      maxDurability: 60,
      miningSpeedMultiplier: 2,
      attackDamage: 2,
    },
    description: "돌과 광석을 채굴할 수 있는 기본적인 나무 곡괭이입니다.",
  },
  [BlockType.WOODEN_SWORD]: {
    id: BlockType.WOODEN_SWORD,
    name: "Wooden Sword",
    nameKo: "나무 검",
    solid: false,
    transparent: true,
    color: "#b45309",
    textureType: "wooden_sword",
    soundType: "wood",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 4,
    toolStats: {
      toolType: "sword",
      material: "wood",
      maxDurability: 60,
      miningSpeedMultiplier: 1.5,
      attackDamage: 4,
    },
    description: "몬스터로부터 몸을 보호할 수 있는 초보 모험가의 나무 검입니다.",
  },
  [BlockType.WOODEN_AXE]: {
    id: BlockType.WOODEN_AXE,
    name: "Wooden Axe",
    nameKo: "나무 도끼",
    solid: false,
    transparent: true,
    color: "#b45309",
    textureType: "wooden_axe",
    soundType: "wood",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 3,
    toolStats: {
      toolType: "axe",
      material: "wood",
      maxDurability: 60,
      miningSpeedMultiplier: 2,
      attackDamage: 3,
    },
    description: "나무 원목을 빠르게 베어낼 수 있는 튼튼한 나무 도끼입니다.",
  },
  [BlockType.ROTTEN_FLESH]: {
    id: BlockType.ROTTEN_FLESH,
    name: "Rotten Flesh",
    nameKo: "썩은 살점 (좀비 드롭)",
    solid: false,
    transparent: true,
    color: "#9a3412",
    textureType: "rotten_flesh",
    soundType: "dirt",
    category: "item",
    isPlaceable: false,
    description: "좀비를 물리치고 획득한 기괴한 고기 조각입니다.",
  },
  [BlockType.SLIME_BALL]: {
    id: BlockType.SLIME_BALL,
    name: "Slimeball",
    nameKo: "슬라임 볼",
    solid: false,
    transparent: true,
    color: "#4ade80",
    textureType: "slimeball",
    soundType: "cloth",
    category: "item",
    isPlaceable: false,
    description: "슬라임을 처치하고 얻은 끈적끈적한 젤리 덩어리입니다.",
  },
  [BlockType.BONE]: {
    id: BlockType.BONE,
    name: "Bone",
    nameKo: "뼈",
    solid: false,
    transparent: true,
    color: "#e2e8f0",
    textureType: "bone",
    soundType: "stone",
    category: "item",
    isPlaceable: false,
    description: "사냥을 통해 얻은 뼛조각입니다.",
  },
  [BlockType.DIAMOND]: {
    id: BlockType.DIAMOND,
    name: "Diamond Gem",
    nameKo: "다이아몬드 보석",
    solid: false,
    transparent: true,
    color: "#38bdf8",
    textureType: "diamond_gem",
    soundType: "metal",
    category: "item",
    isPlaceable: false,
    description: "영롱하게 빛나는 가장 귀중하고 단단한 보석입니다.",
  },
  [BlockType.BREAD]: {
    id: BlockType.BREAD,
    name: "Bread",
    nameKo: "갓 구운 빵",
    solid: false,
    transparent: true,
    color: "#d97706",
    textureType: "bread",
    soundType: "cloth",
    category: "item",
    isPlaceable: false,
    description: "밀 3개를 조합하여 만든 든든한 빵입니다. 우클릭 시 체력을 회복합니다.",
  },
  [BlockType.ZOMBIE_SPAWN_EGG]: {
    id: BlockType.ZOMBIE_SPAWN_EGG,
    name: "Zombie Spawn Egg",
    nameKo: "좀비 소환 알",
    solid: false,
    transparent: true,
    color: "#059669",
    textureType: "zombie_egg",
    soundType: "dirt",
    category: "egg",
    isEgg: true,
    spawnType: "zombie",
    isPlaceable: false,
    description: "지면에 우클릭하면 무시무시한 좀비를 즉시 소환합니다.",
  },
  [BlockType.SLIME_SPAWN_EGG]: {
    id: BlockType.SLIME_SPAWN_EGG,
    name: "Slime Spawn Egg",
    nameKo: "슬라임 소환 알",
    solid: false,
    transparent: true,
    color: "#22c55e",
    textureType: "slime_egg",
    soundType: "cloth",
    category: "egg",
    isEgg: true,
    spawnType: "slime",
    isPlaceable: false,
    description: "지면에 우클릭하면 통통 튀는 귀여운 슬라임을 즉시 소환합니다.",
  },
  [BlockType.TORCH]: {
    id: BlockType.TORCH,
    name: "Torch",
    nameKo: "횃불",
    solid: false,
    transparent: true,
    color: "#fbbf24",
    textureType: "torch",
    soundType: "wood",
    category: "block",
    isPlaceable: true,
    lightLevel: 14,
    description: "주변을 환하게 밝혀주고 밤에 몬스터가 소환되는 것을 방지합니다.",
  },
  [BlockType.WATER]: {
    id: BlockType.WATER,
    name: "Water",
    nameKo: "물",
    solid: false,
    transparent: true,
    color: "#3b82f6",
    textureType: "water",
    soundType: "glass",
    category: "block",
    isPlaceable: true,
    isFluid: true,
    description: "낮은 곳과 주변으로 자연스럽게 흘러 퍼져나가는 유체 블록입니다.",
  },
  [BlockType.GRAVEL]: {
    id: BlockType.GRAVEL,
    name: "Gravel",
    nameKo: "자갈",
    solid: true,
    transparent: false,
    color: "#6b7280",
    textureType: "gravel",
    soundType: "sand",
    category: "block",
    isPlaceable: true,
    gravityAffected: true,
    hardness: 0.6,
    preferredTool: "shovel",
    description: "바닥에 지지대가 없으면 아래로 떨어지는 중력 영향을 받는 자갈입니다.",
  },
  [BlockType.COAL]: {
    id: BlockType.COAL,
    name: "Coal",
    nameKo: "석탄",
    solid: false,
    transparent: true,
    color: "#1f2937",
    textureType: "coal",
    soundType: "stone",
    category: "item",
    isPlaceable: false,
    description: "횃불을 제작할 때 쓰이는 소중한 연료입니다.",
  },
  [BlockType.IRON_INGOT]: {
    id: BlockType.IRON_INGOT,
    name: "Iron Ingot",
    nameKo: "철괴",
    solid: false,
    transparent: true,
    color: "#e2e8f0",
    textureType: "iron_ingot",
    soundType: "metal",
    category: "item",
    isPlaceable: false,
    description: "견고한 철제 도구와 무기를 제련할 때 사용됩니다.",
  },
  [BlockType.IRON_PICKAXE]: {
    id: BlockType.IRON_PICKAXE,
    name: "Iron Pickaxe",
    nameKo: "철 곡괭이",
    solid: false,
    transparent: true,
    color: "#cbd5e1",
    textureType: "iron_pickaxe",
    soundType: "metal",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 4,
    toolStats: {
      toolType: "pickaxe",
      material: "iron",
      maxDurability: 250,
      miningSpeedMultiplier: 6,
      attackDamage: 4,
    },
    description: "단단한 바위와 광석을 빠른 속도로 채굴하는 철 곡괭이입니다.",
  },
  [BlockType.IRON_AXE]: {
    id: BlockType.IRON_AXE,
    name: "Iron Axe",
    nameKo: "철 도끼",
    solid: false,
    transparent: true,
    color: "#cbd5e1",
    textureType: "iron_axe",
    soundType: "metal",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 5,
    toolStats: {
      toolType: "axe",
      material: "iron",
      maxDurability: 250,
      miningSpeedMultiplier: 6,
      attackDamage: 5,
    },
    description: "나무를 신속하게 벌목할 수 있는 견고한 철 도끼입니다.",
  },
  [BlockType.IRON_SHOVEL]: {
    id: BlockType.IRON_SHOVEL,
    name: "Iron Shovel",
    nameKo: "철 삽",
    solid: false,
    transparent: true,
    color: "#cbd5e1",
    textureType: "iron_shovel",
    soundType: "metal",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 3,
    toolStats: {
      toolType: "shovel",
      material: "iron",
      maxDurability: 250,
      miningSpeedMultiplier: 6,
      attackDamage: 3,
    },
    description: "흙, 모래, 자갈을 빠르게 퍼낼 수 있는 철 삽입니다.",
  },
  [BlockType.IRON_SWORD]: {
    id: BlockType.IRON_SWORD,
    name: "Iron Sword",
    nameKo: "철 검",
    solid: false,
    transparent: true,
    color: "#cbd5e1",
    textureType: "iron_sword",
    soundType: "metal",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 6,
    toolStats: {
      toolType: "sword",
      material: "iron",
      maxDurability: 250,
      miningSpeedMultiplier: 2,
      attackDamage: 6,
    },
    description: "몬스터에게 강력한 데미지를 입히는 날카로운 철 검입니다.",
  },
  [BlockType.WOODEN_SHOVEL]: {
    id: BlockType.WOODEN_SHOVEL,
    name: "Wooden Shovel",
    nameKo: "나무 삽",
    solid: false,
    transparent: true,
    color: "#b45309",
    textureType: "wooden_shovel",
    soundType: "wood",
    category: "tool",
    isTool: true,
    isPlaceable: false,
    damage: 2,
    toolStats: {
      toolType: "shovel",
      material: "wood",
      maxDurability: 60,
      miningSpeedMultiplier: 2.5,
      attackDamage: 2,
    },
    description: "흙과 모래를 파내는 나무 삽입니다.",
  },
  [BlockType.SNOW]: {
    id: BlockType.SNOW,
    name: "Snow Block",
    nameKo: "눈 블록",
    solid: true,
    transparent: false,
    color: "#f8fafc",
    textureType: "snow",
    soundType: "sand",
    category: "block",
    isPlaceable: true,
    hardness: 0.4,
    preferredTool: "shovel",
    description: "높은 산꼭대기를 뒤덮은 차가운 눈 블록입니다.",
  },
};

export interface UserAccount {
  id: string;
  username: string;
  token: string;
}

export interface InventorySlotItem {
  blockType: BlockType;
  count: number;
}

export interface CraftingRecipe {
  id: string;
  name: string;
  nameKo: string;
  is3x3Only?: boolean;
  pattern?: string[]; // e.g. ["P", "S"] or ["PPP", " S ", " S "]
  key?: Record<string, BlockType>;
  shapeless?: BlockType[];
  result: {
    blockType: BlockType;
    count: number;
  };
}

export interface DroppedItemEntity {
  id: string;
  blockType: BlockType;
  count: number;
  position: [number, number, number];
}

export interface PlayerData {
  id: string;
  socketId: string;
  nickname: string;
  position: [number, number, number];
  rotation: [number, number]; // [pitch, yaw]
  selectedBlock: BlockType;
  color: string;
  isHost?: boolean;
}

export interface RoomState {
  code: string;
  hostId: string;
  players: PlayerData[];
  seed: number;
  started: boolean;
  maxPlayers: number;
  modifiedBlocks?: Record<string, number>;
}

export interface ChatMessage {
  id: string;
  senderId: string;
  senderName: string;
  color: string;
  message: string;
  timestamp: number;
}

export interface RaycastResult {
  hit: boolean;
  point?: [number, number, number];
  blockPos?: [number, number, number];
  faceNormal?: [number, number, number];
  blockType?: BlockType;
  distance?: number;
}
